# [START runtime]
runtime: python27
threadsafe: yes
# [END runtime]
handlers:
- url: /(.+)
  static_files: dist/\1
  upload: dist/(.*)
- url: /
  static_files: dist/factor-ui/index.html
  upload: dist/factor-ui/index.html
skip_files:
- ^(?!dist)  # Skip any files not in the dist folder
